apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-datasets
  namespace: edhenry
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/datasets"
    type: Directory