# kind: Pod
# apiVersion: v1
# metadata:
#   name: pod-using-nfs
# spec:
#   # Add the server as an NFS volume for the pod
#   volumes:
#   - name: my-pvc-nfs
#     persistentVolumeClaim:
#       claimName: lts-bot-data-claim

#   # In this container, we'll mount the NFS volume
#   # and write the date to a file inside it.
#   containers:
#     - name: app
#       image: alpine

#       # Mount the NFS volume in the container
#       volumeMounts:
#         - name: my-pvc-nfs
#           mountPath: /var/nfs

apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
spec:
  volumes:
  - name: my-pvc-nfs
    persistentVolumeClaim:
      claimName: lts-bot-data-claim
  
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: my-pvc-nfs
      mountPath: /usr/share/nginx/html
  # hostNetwork: true
  # dnsPolicy: Default