apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lts-bot-data-claim
  namespace: kubeflow
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi